# Generated by Django 4.1 on 2024-02-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='mobile_number',
            new_name='place_of_birth',
        ),
    ]
