# Generated by Django 4.1 on 2024-02-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_mobile_number_userdetails_place_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='place_of_birth',
            new_name='placeOfBirth',
        ),
    ]
