# Generated by Django 4.1 on 2024-02-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_date_of_birth_userdetails_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='placeOfBirth',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='firstName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
